POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "How I beat Voldemort",
    "author": "Harry Potter",
    "url": "www.hogwarts.com/harry",
    "likes": 3
}
