POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlcjIiLCJpZCI6IjY1N2M3MTJkYzhmNjY2NTk1Yjc1NDkzYiIsImlhdCI6MTcwNDgxODY3OX0.aYh7jVhFHdZRN_mykAfVx-ieIythtaLFzx_WOnewCNI

{
    "title": "Test after extracting token using middleware",
    "author": "FullStackOpen",
    "url": "www.fullstackopen.com/en/part4/token_authentication",
    "likes": 23
}
